# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Graph Processing Musings
tagline:             'Random thoughts on recent research trends'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Marcus Paradies
  url:               https://www.google.com
  email:             graphprocessingmusings@gmail.com

# Custom vars
version:             1.0.0
