# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Graph Processing Musings
tagline:             'Random thoughts on recent research trends'
url:                 http://graphprocessingmusings.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Marcus Paradies
  url:               https://wwwdb.inf.tu-dresden.de/team/external-members/marcus-paradies/
  email:             graphprocessingmusings@gmail.com

# Custom vars
version:             1.0.0
